openapi: 3.2.0
info:
  title: DigitalOcean Uptime API
  version: '2.0'
  description: '# Introduction


    The DigitalOcean API allows you to manage Droplets and resources within the

    DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: https://www.digitalocean.com/legal/terms-of-service-agreement/
servers:
- url: https://api.digitalocean.com
  description: production
security:
- bearer_auth: []
tags:
- name: Uptime
  description: 'DigitalOcean Uptime Checks provide the ability to monitor your endpoints from around the world, and alert you when they''re slow, unavailable, or SSL certificates are expiring.

    To interact with Uptime, you will generally send requests to the Uptime endpoint at `/v2/uptime/`.'
paths:
  /v2/uptime/checks:
    get:
      operationId: uptime_list_checks
      summary: List All Checks
      description: To list all of the Uptime checks on your account, send a GET request to `/v2/uptime/checks`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:read
    post:
      operationId: uptime_create_check
      summary: Create a New Check
      description: 'To create an Uptime check, send a POST request to `/v2/uptime/checks` specifying the attributes

        in the table below in the JSON body.'
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:create
  /v2/uptime/checks/{check_id}:
    get:
      operationId: uptime_get_check
      summary: Retrieve an Existing Check
      description: To show information about an existing check, send a GET request to `/v2/uptime/checks/$CHECK_ID`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:read
    put:
      operationId: uptime_update_check
      summary: Update a Check
      description: To update the settings of an Uptime check, send a PUT request to `/v2/uptime/checks/$CHECK_ID`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:update
    delete:
      operationId: uptime_delete_check
      summary: Delete a Check
      description: 'To delete an Uptime check, send a DELETE request to `/v2/uptime/checks/$CHECK_ID`. A 204 status

        code with no body will be returned in response to a successful request.


        Deleting a check will also delete alerts associated with the check.'
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:delete
  /v2/uptime/checks/{check_id}/state:
    get:
      operationId: uptime_get_checkState
      summary: Retrieve Check State
      description: To show information about an existing check's state, send a GET request to `/v2/uptime/checks/$CHECK_ID/state`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:read
  /v2/uptime/checks/{check_id}/alerts:
    get:
      operationId: uptime_list_alerts
      summary: List All Alerts
      description: To list all of the alerts for an Uptime check, send a GET request to `/v2/uptime/checks/$CHECK_ID/alerts`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:read
    post:
      operationId: uptime_create_alert
      summary: Create a New Alert
      description: 'To create an Uptime alert, send a POST request to `/v2/uptime/checks/$CHECK_ID/alerts` specifying the attributes

        in the table below in the JSON body.'
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:create
  /v2/uptime/checks/{check_id}/alerts/{alert_id}:
    get:
      operationId: uptime_get_alert
      summary: Retrieve an Existing Alert
      description: To show information about an existing alert, send a GET request to `/v2/uptime/checks/$CHECK_ID/alerts/$ALERT_ID`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:read
    put:
      operationId: uptime_update_alert
      summary: Update an Alert
      description: To update the settings of an Uptime alert, send a PUT request to `/v2/uptime/checks/$CHECK_ID/alerts/$ALERT_ID`.
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:update
    delete:
      operationId: uptime_delete_alert
      summary: Delete an Alert
      description: 'To delete an Uptime alert, send a DELETE request to `/v2/uptime/checks/$CHECK_ID/alerts/$ALERT_ID`. A 204 status

        code with no body will be returned in response to a successful request.'
      tags:
      - Uptime
      security:
      - bearer_auth:
        - uptime:delete
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: '## OAuth Authentication


        In order to interact with the DigitalOcean API, you or your application must

        authenticate.


        The DigitalOcean API handles this through OAuth, an open standard for

        authorization. OAuth allows you to delegate access to your account.

        Scopes can be used to grant full access, read-only access, or access to

        a specific set of endpoints.


        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)

        section of the DigitalOcean control panel for your account.


        An OAuth token functions as a complete authentication request. In effect, it

        acts as a substitute for a username and password pair.


        Because of this, it is absolutely **essential** that you keep your OAuth

        tokens secure. In fact, upon generation, the web interface will only display

        each token a single time in order to prevent the token from being compromised.


        DigitalOcean access tokens begin with an identifiable prefix in order to

        distinguish them from other similar tokens.


        - `dop_v1_` for personal access tokens generated in the control panel

        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)

        - `dor_v1_` for OAuth refresh tokens


        ### Scopes


        Scopes act like permissions assigned to an API token. These permissions

        determine what actions the token can perform. You can create API

        tokens that grant read-only access, full access, or limited access to

        specific endpoints by using custom scopes.


        Generally, scopes are designed to match HTTP verbs and common CRUD

        operations (Create, Read, Update, Delete).


        | HTTP Verb | CRUD Operation | Scope |

        |---|---|---|

        | GET | Read | `<resource>:read` |

        | POST | Create | `<resource>:create` |

        | PUT/PATCH | Update | `<resource>:update` |

        | DELETE | Delete | `<resource>:delete` |


        For example, creating a new Droplet by making a `POST` request to the

        `/v2/droplets` endpoint requires the `droplet:create` scope while

        listing Droplets by making a `GET` request to the `/v2/droplets`

        endpoint requires the `droplet:read` scope.


        Each endpoint below specifies which scope is required to access it when

        using custom scopes.


        ### How to Authenticate with OAuth


        In order to make an authenticated request, include a bearer-type

        `Authorization` header containing your OAuth token. All requests must be

        made over HTTPS.


        ### Authenticate with a Bearer Authorization Header


        ```

        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"

        ```

        '
