openapi: 3.2.0
info:
  title: DigitalOcean Firewalls API
  version: '2.0'
  description: '# Introduction


    The DigitalOcean API allows you to manage Droplets and resources within the

    DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: https://www.digitalocean.com/legal/terms-of-service-agreement/
servers:
- url: https://api.digitalocean.com
  description: production
security:
- bearer_auth: []
tags:
- name: Firewalls
  description: 'DigitalOcean Cloud Firewalls

    provide the ability to restrict network access to and from a Droplet

    allowing you to define which ports will accept inbound or outbound

    connections. By sending requests to the `/v2/firewalls` endpoint, you can

    list, create, or delete firewalls as well as modify access rules.'
paths:
  /v2/firewalls:
    get:
      operationId: firewalls_list
      summary: List All Firewalls
      description: To list all of the firewalls available on your account, send a GET request to `/v2/firewalls`.
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:read
    post:
      operationId: firewalls_create
      summary: Create a New Firewall
      description: 'To create a new firewall, send a POST request to `/v2/firewalls`. The request

        must contain at least one inbound or outbound access rule.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:create
  /v2/firewalls/{firewall_id}:
    get:
      operationId: firewalls_get
      summary: Retrieve an Existing Firewall
      description: To show information about an existing firewall, send a GET request to `/v2/firewalls/$FIREWALL_ID`.
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:read
    put:
      operationId: firewalls_update
      summary: Update a Firewall
      description: 'To update the configuration of an existing firewall, send a PUT request to

        `/v2/firewalls/$FIREWALL_ID`. The request should contain a full representation

        of the firewall including existing attributes. **Note that any attributes that

        are not provided will be reset to their default values.**'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
    delete:
      operationId: firewalls_delete
      summary: Delete a Firewall
      description: 'To delete a firewall send a DELETE request to `/v2/firewalls/$FIREWALL_ID`.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:delete
  /v2/firewalls/{firewall_id}/droplets:
    post:
      operationId: firewalls_assign_droplets
      summary: Add Droplets to a Firewall
      description: 'To assign a Droplet to a firewall, send a POST request to

        `/v2/firewalls/$FIREWALL_ID/droplets`. In the body of the request, there

        should be a `droplet_ids` attribute containing a list of Droplet IDs.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
    delete:
      operationId: firewalls_delete_droplets
      summary: Remove Droplets from a Firewall
      description: 'To remove a Droplet from a firewall, send a DELETE request to

        `/v2/firewalls/$FIREWALL_ID/droplets`. In the body of the request, there should

        be a `droplet_ids` attribute containing a list of Droplet IDs.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
  /v2/firewalls/{firewall_id}/tags:
    post:
      operationId: firewalls_add_tags
      summary: Add Tags to a Firewall
      description: 'To assign a tag representing a group of Droplets to a firewall, send a POST

        request to `/v2/firewalls/$FIREWALL_ID/tags`. In the body of the request,

        there should be a `tags` attribute containing a list of tag names.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
    delete:
      operationId: firewalls_delete_tags
      summary: Remove Tags from a Firewall
      description: 'To remove a tag representing a group of Droplets from a firewall, send a

        DELETE request to `/v2/firewalls/$FIREWALL_ID/tags`. In the body of the

        request, there should be a `tags` attribute containing a list of tag names.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
  /v2/firewalls/{firewall_id}/rules:
    post:
      operationId: firewalls_add_rules
      summary: Add Rules to a Firewall
      description: 'To add additional access rules to a firewall, send a POST request to

        `/v2/firewalls/$FIREWALL_ID/rules`. The body of the request may include an

        inbound_rules and/or outbound_rules attribute containing an array of rules to

        be added.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
    delete:
      operationId: firewalls_delete_rules
      summary: Remove Rules from a Firewall
      description: 'To remove access rules from a firewall, send a DELETE request to

        `/v2/firewalls/$FIREWALL_ID/rules`. The body of the request may include an

        `inbound_rules` and/or `outbound_rules` attribute containing an array of rules

        to be removed.


        No response body will be sent back, but the response code will indicate

        success. Specifically, the response code will be a 204, which means that the

        action was successful with no returned body data.'
      tags:
      - Firewalls
      security:
      - bearer_auth:
        - firewall:update
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: '## OAuth Authentication


        In order to interact with the DigitalOcean API, you or your application must

        authenticate.


        The DigitalOcean API handles this through OAuth, an open standard for

        authorization. OAuth allows you to delegate access to your account.

        Scopes can be used to grant full access, read-only access, or access to

        a specific set of endpoints.


        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)

        section of the DigitalOcean control panel for your account.


        An OAuth token functions as a complete authentication request. In effect, it

        acts as a substitute for a username and password pair.


        Because of this, it is absolutely **essential** that you keep your OAuth

        tokens secure. In fact, upon generation, the web interface will only display

        each token a single time in order to prevent the token from being compromised.


        DigitalOcean access tokens begin with an identifiable prefix in order to

        distinguish them from other similar tokens.


        - `dop_v1_` for personal access tokens generated in the control panel

        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)

        - `dor_v1_` for OAuth refresh tokens


        ### Scopes


        Scopes act like permissions assigned to an API token. These permissions

        determine what actions the token can perform. You can create API

        tokens that grant read-only access, full access, or limited access to

        specific endpoints by using custom scopes.


        Generally, scopes are designed to match HTTP verbs and common CRUD

        operations (Create, Read, Update, Delete).


        | HTTP Verb | CRUD Operation | Scope |

        |---|---|---|

        | GET | Read | `<resource>:read` |

        | POST | Create | `<resource>:create` |

        | PUT/PATCH | Update | `<resource>:update` |

        | DELETE | Delete | `<resource>:delete` |


        For example, creating a new Droplet by making a `POST` request to the

        `/v2/droplets` endpoint requires the `droplet:create` scope while

        listing Droplets by making a `GET` request to the `/v2/droplets`

        endpoint requires the `droplet:read` scope.


        Each endpoint below specifies which scope is required to access it when

        using custom scopes.


        ### How to Authenticate with OAuth


        In order to make an authenticated request, include a bearer-type

        `Authorization` header containing your OAuth token. All requests must be

        made over HTTPS.


        ### Authenticate with a Bearer Authorization Header


        ```

        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"

        ```

        '
