openapi: 3.2.0
info:
  title: DigitalOcean VP Cs API
  version: '2.0'
  description: '# Introduction


    The DigitalOcean API allows you to manage Droplets and resources within the

    DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: https://www.digitalocean.com/legal/terms-of-service-agreement/
servers:
- url: https://api.digitalocean.com
  description: production
security:
- bearer_auth: []
tags:
- name: VPCs
  description: 'VPCs (virtual private clouds)

    allow you to create virtual networks containing resources that can

    communicate with each other in full isolation using private IP addresses.


    By sending requests to the `/v2/vpcs` endpoint, you can create, configure,

    list, and delete custom VPCs as well as retrieve information about the

    resources assigned to them.'
paths:
  /v2/vpcs:
    get:
      operationId: vpcs_list
      summary: List All VPCs
      description: To list all of the VPCs on your account, send a GET request to `/v2/vpcs`.
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:read
    post:
      operationId: vpcs_create
      summary: Create a New VPC
      description: 'To create a VPC, send a POST request to `/v2/vpcs` specifying the attributes

        in the table below in the JSON body.


        **Note:** If you do not currently have a VPC network in a specific datacenter

        region, the first one that you create will be set as the default for that

        region. The default VPC for a region cannot be changed or deleted.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:create
  /v2/vpcs/{vpc_id}:
    get:
      operationId: vpcs_get
      summary: Retrieve an Existing VPC
      description: To show information about an existing VPC, send a GET request to `/v2/vpcs/$VPC_ID`.
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:read
    put:
      operationId: vpcs_update
      summary: Update a VPC
      description: To update information about a VPC, send a PUT request to `/v2/vpcs/$VPC_ID`.
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:update
    patch:
      operationId: vpcs_patch
      summary: Partially Update a VPC
      description: 'To update a subset of information about a VPC, send a PATCH request to

        `/v2/vpcs/$VPC_ID`.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:update
    delete:
      operationId: vpcs_delete
      summary: Delete a VPC
      description: 'To delete a VPC, send a DELETE request to `/v2/vpcs/$VPC_ID`. A 204 status

        code with no body will be returned in response to a successful request.


        The default VPC for a region can not be deleted. Additionally, a VPC can only

        be deleted if it does not contain any member resources. Attempting to delete

        a region''s default VPC or a VPC that still has members will result in a

        403 Forbidden error response.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:delete
  /v2/vpcs/{vpc_id}/members:
    get:
      operationId: vpcs_list_members
      summary: List the Member Resources of a VPC
      description: 'To list all of the resources that are members of a VPC, send a GET request to

        `/v2/vpcs/$VPC_ID/members`.


        To only list resources of a specific type that are members of the VPC,

        included a `resource_type` query parameter. For example, to only list Droplets

        in the VPC, send a GET request to `/v2/vpcs/$VPC_ID/members?resource_type=droplet`.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc:read
  /v2/vpcs/{vpc_id}/peerings:
    get:
      operationId: vpcs_list_peerings
      summary: List the Peerings of a VPC
      description: 'To list all of a VPC''s peerings, send a GET request to

        `/v2/vpcs/$VPC_ID/peerings`.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc_peering:read
    post:
      operationId: vpcs_create_peerings
      summary: Create a Peering with a VPC
      description: 'To create a new VPC peering for a given VPC, send a POST request to

        `/v2/vpcs/$VPC_ID/peerings`.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc_peering:create
  /v2/vpcs/{vpc_id}/peerings/{vpc_peering_id}:
    patch:
      operationId: vpcs_patch_peerings
      summary: Update a VPC Peering
      description: 'To update the name of a VPC peering in a particular VPC, send a PATCH request

        to `/v2/vpcs/$VPC_ID/peerings/$VPC_PEERING_ID` with the new `name` in the

        request body.'
      tags:
      - VPCs
      security:
      - bearer_auth:
        - vpc_peering:update
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: '## OAuth Authentication


        In order to interact with the DigitalOcean API, you or your application must

        authenticate.


        The DigitalOcean API handles this through OAuth, an open standard for

        authorization. OAuth allows you to delegate access to your account.

        Scopes can be used to grant full access, read-only access, or access to

        a specific set of endpoints.


        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)

        section of the DigitalOcean control panel for your account.


        An OAuth token functions as a complete authentication request. In effect, it

        acts as a substitute for a username and password pair.


        Because of this, it is absolutely **essential** that you keep your OAuth

        tokens secure. In fact, upon generation, the web interface will only display

        each token a single time in order to prevent the token from being compromised.


        DigitalOcean access tokens begin with an identifiable prefix in order to

        distinguish them from other similar tokens.


        - `dop_v1_` for personal access tokens generated in the control panel

        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)

        - `dor_v1_` for OAuth refresh tokens


        ### Scopes


        Scopes act like permissions assigned to an API token. These permissions

        determine what actions the token can perform. You can create API

        tokens that grant read-only access, full access, or limited access to

        specific endpoints by using custom scopes.


        Generally, scopes are designed to match HTTP verbs and common CRUD

        operations (Create, Read, Update, Delete).


        | HTTP Verb | CRUD Operation | Scope |

        |---|---|---|

        | GET | Read | `<resource>:read` |

        | POST | Create | `<resource>:create` |

        | PUT/PATCH | Update | `<resource>:update` |

        | DELETE | Delete | `<resource>:delete` |


        For example, creating a new Droplet by making a `POST` request to the

        `/v2/droplets` endpoint requires the `droplet:create` scope while

        listing Droplets by making a `GET` request to the `/v2/droplets`

        endpoint requires the `droplet:read` scope.


        Each endpoint below specifies which scope is required to access it when

        using custom scopes.


        ### How to Authenticate with OAuth


        In order to make an authenticated request, include a bearer-type

        `Authorization` header containing your OAuth token. All requests must be

        made over HTTPS.


        ### Authenticate with a Bearer Authorization Header


        ```

        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"

        ```

        '
