openapi: 3.2.0
info:
  title: DigitalOcean Monitoring API
  version: '2.0'
  description: '# Introduction


    The DigitalOcean API allows you to manage Droplets and resources within the

    DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: https://www.digitalocean.com/legal/terms-of-service-agreement/
servers:
- url: https://api.digitalocean.com
  description: production
security:
- bearer_auth: []
tags:
- name: Monitoring
  description: 'The DigitalOcean Monitoring API makes it possible to programmatically retrieve metrics as well as configure alert

    policies based on these metrics. The Monitoring API can help you gain insight into how your apps are performing

    and consuming resources.'
paths:
  /v2/monitoring/alerts:
    get:
      operationId: monitoring_list_alertPolicy
      summary: List Alert Policies
      description: Returns all alert policies that are configured for the given account. To List all alert policies, send a GET request to `/v2/monitoring/alerts`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
    post:
      operationId: monitoring_create_alertPolicy
      summary: Create Alert Policy
      description: To create a new alert, send a POST request to `/v2/monitoring/alerts`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:create
  /v2/monitoring/alerts/{alert_uuid}:
    get:
      operationId: monitoring_get_alertPolicy
      summary: Retrieve an Existing Alert Policy
      description: To retrieve a given alert policy, send a GET request to `/v2/monitoring/alerts/{alert_uuid}`
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
    put:
      operationId: monitoring_update_alertPolicy
      summary: Update an Alert Policy
      description: To update en existing policy, send a PUT request to `v2/monitoring/alerts/{alert_uuid}`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:update
    delete:
      operationId: monitoring_delete_alertPolicy
      summary: Delete an Alert Policy
      description: To delete an alert policy, send a DELETE request to `/v2/monitoring/alerts/{alert_uuid}`
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:delete
  /v2/monitoring/metrics/droplet/bandwidth:
    get:
      operationId: monitoring_get_dropletBandwidthMetrics
      summary: Get Droplet Bandwidth Metrics
      description: 'To retrieve bandwidth metrics for a given Droplet, send a GET request to `/v2/monitoring/metrics/droplet/bandwidth`. Use the `interface` query parameter to specify if the results should be for the `private` or `public` interface. Use the `direction` query parameter to specify if the results should be for `inbound` or `outbound` traffic.

        The metrics in the response body are in megabits per second (Mbps).'
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/cpu:
    get:
      operationId: monitoring_get_DropletCpuMetrics
      summary: Get Droplet CPU Metrics
      description: To retrieve CPU metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/cpu`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/filesystem_free:
    get:
      operationId: monitoring_get_dropletFilesystemFreeMetrics
      summary: Get Droplet Filesystem Free Metrics
      description: To retrieve filesystem free metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/filesystem_free`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/filesystem_size:
    get:
      operationId: monitoring_get_dropletFilesystemSizeMetrics
      summary: Get Droplet Filesystem Size Metrics
      description: To retrieve filesystem size metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/filesystem_size`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/load_1:
    get:
      operationId: monitoring_get_dropletLoad1Metrics
      summary: Get Droplet Load1 Metrics
      description: To retrieve 1 minute load average metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/load_1`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/load_5:
    get:
      operationId: monitoring_get_dropletLoad5Metrics
      summary: Get Droplet Load5 Metrics
      description: To retrieve 5 minute load average metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/load_5`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/load_15:
    get:
      operationId: monitoring_get_dropletLoad15Metrics
      summary: Get Droplet Load15 Metrics
      description: To retrieve 15 minute load average metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/load_15`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/memory_cached:
    get:
      operationId: monitoring_get_dropletMemoryCachedMetrics
      summary: Get Droplet Cached Memory Metrics
      description: To retrieve cached memory metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/memory_cached`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/memory_free:
    get:
      operationId: monitoring_get_dropletMemoryFreeMetrics
      summary: Get Droplet Free Memory Metrics
      description: To retrieve free memory metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/memory_free`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/memory_total:
    get:
      operationId: monitoring_get_dropletMemoryTotalMetrics
      summary: Get Droplet Total Memory Metrics
      description: To retrieve total memory metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/memory_total`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/droplet/memory_available:
    get:
      operationId: monitoring_get_dropletMemoryAvailableMetrics
      summary: Get Droplet Available Memory Metrics
      description: To retrieve available memory metrics for a given droplet, send a GET request to `/v2/monitoring/metrics/droplet/memory_available`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/apps/memory_percentage:
    get:
      operationId: monitoring_get_appMemoryPercentageMetrics
      summary: Get App Memory Percentage Metrics
      description: To retrieve memory percentage metrics for a given app, send a GET request to `/v2/monitoring/metrics/apps/memory_percentage`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/apps/cpu_percentage:
    get:
      operationId: monitoring_get_appCPUPercentageMetrics
      summary: Get App CPU Percentage Metrics
      description: To retrieve cpu percentage metrics for a given app, send a GET request to `/v2/monitoring/metrics/apps/cpu_percentage`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/apps/restart_count:
    get:
      operationId: monitoring_get_appRestartCountMetrics.yml
      summary: Get App Restart Count Metrics
      description: To retrieve restart count metrics for a given app, send a GET request to `/v2/monitoring/metrics/apps/restart_count`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_connections_current:
    get:
      operationId: monitoring_get_lb_frontend_connections_current
      summary: Get Load Balancer Frontend Total Current Active Connections Metrics
      description: To retrieve frontend total current active connections for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_connections_current`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_connections_limit:
    get:
      operationId: monitoring_get_lb_frontend_connections_limit
      summary: Get Load Balancer Frontend Max Connections Limit Metrics
      description: To retrieve frontend max connections limit for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_connections_limit`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_cpu_utilization:
    get:
      operationId: monitoring_get_lb_frontend_cpu_utilization
      summary: Get Load Balancer Frontend Average Percentage CPU Utilization Metrics
      description: To retrieve frontend average percentage CPU utilization for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_cpu_utilization`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_bytes:
    get:
      operationId: monitoring_get_lb_frontend_firewall_dropped_bytes
      summary: Get Load Balancer Frontend Firewall Dropped Bytes Metrics
      description: To retrieve firewall dropped bytes for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_bytes`. This is currently only supported for network load balancers.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_packets:
    get:
      operationId: monitoring_get_lb_frontend_firewall_dropped_packets
      summary: Get Load Balancer Frontend Firewall Dropped Packets Metrics
      description: To retrieve firewall dropped packets per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_packets`. This is currently only supported for network load balancers.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_http_responses:
    get:
      operationId: monitoring_get_lb_frontend_http_responses
      summary: Get Load Balancer Frontend HTTP Rate Of Response Code Metrics
      description: To retrieve frontend HTTP rate of response code for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_http_responses`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_http_requests_per_second:
    get:
      operationId: monitoring_get_lb_frontend_http_requests_per_second
      summary: Get Load Balancer Frontend HTTP Requests Metrics
      description: To retrieve frontend HTTP requests per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_http_requests_per_second`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_network_throughput_http:
    get:
      operationId: monitoring_get_lb_frontend_network_throughput_http
      summary: Get Load Balancer Frontend HTTP Throughput Metrics
      description: To retrieve frontend HTTP throughput in bytes per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_network_throughput_http`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_network_throughput_udp:
    get:
      operationId: monitoring_get_lb_frontend_network_throughput_udp
      summary: Get Load Balancer Frontend UDP Throughput Metrics
      description: To retrieve frontend UDP throughput in bytes per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_network_throughput_udp`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_network_throughput_tcp:
    get:
      operationId: monitoring_get_lb_frontend_network_throughput_tcp
      summary: Get Load Balancer Frontend TCP Throughput Metrics
      description: To retrieve frontend TCP throughput in bytes per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_network_throughput_tcp`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_nlb_tcp_network_throughput:
    get:
      operationId: monitoring_get_lb_frontend_nlb_tcp_network_throughput
      summary: Get Network Load Balancer Frontend TCP Throughput Metrics
      description: To retrieve frontend TCP throughput in bytes per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_nlb_tcp_network_throughput`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_nlb_udp_network_throughput:
    get:
      operationId: monitoring_get_lb_frontend_nlb_udp_network_throughput
      summary: Get Network Load Balancer Frontend UDP Throughput Metrics
      description: To retrieve frontend UDP throughput in bytes per second for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_nlb_udp_network_throughput`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_tls_connections_current:
    get:
      operationId: monitoring_get_lb_frontend_tls_connections_current
      summary: Get Load Balancer Frontend Current TLS Connections Rate Metrics
      description: To retrieve frontend current TLS connections rate for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_tls_connections_current`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_tls_connections_limit:
    get:
      operationId: monitoring_get_lb_frontend_tls_connections_limit
      summary: Get Load Balancer Frontend Max TLS Connections Limit Metrics
      description: To retrieve frontend max TLS connections limit for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_tls_connections_limit`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/frontend_tls_connections_exceeding_rate_limit:
    get:
      operationId: monitoring_get_lb_frontend_tls_connections_exceeding_rate_limit
      summary: Get Load Balancer Frontend Closed TLS Connections For Exceeded Rate Limit…
      description: To retrieve frontend closed TLS connections for exceeded rate limit for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_tls_connections_exceeding_rate_limit`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_session_duration_avg:
    get:
      operationId: monitoring_get_lb_droplets_http_session_duration_avg
      summary: Get Load Balancer Droplets Average HTTP Session Duration Metrics
      description: To retrieve Droplets average HTTP session duration in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_avg`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p:
    get:
      operationId: monitoring_get_lb_droplets_http_session_duration_50p
      summary: Get Load Balancer Droplets 50th Percentile HTTP Session Duration Metrics
      description: To retrieve Droplets 50th percentile HTTP session duration in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_session_duration_95p:
    get:
      operationId: monitoring_get_lb_droplets_http_session_duration_95p
      summary: Get Load Balancer Droplets 95th Percentile HTTP Session Duration Metrics
      description: To retrieve Droplets 95th percentile HTTP session duration in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_95p`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_response_time_avg:
    get:
      operationId: monitoring_get_lb_droplets_http_response_time_avg
      summary: Get Load Balancer Droplets Average HTTP Response Time Metrics
      description: To retrieve Droplets average HTTP response time in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_response_time_avg`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_response_time_50p:
    get:
      operationId: monitoring_get_lb_droplets_http_response_time_50p
      summary: Get Load Balancer Droplets 50th Percentile HTTP Response Time Metrics
      description: To retrieve Droplets 50th percentile HTTP response time in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_response_time_50p`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_response_time_95p:
    get:
      operationId: monitoring_get_lb_droplets_http_response_time_95p
      summary: Get Load Balancer Droplets 95th Percentile HTTP Response Time Metrics
      description: To retrieve Droplets 95th percentile HTTP response time in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_response_time_95p`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_response_time_99p:
    get:
      operationId: monitoring_get_lb_droplets_http_response_time_99p
      summary: Get Load Balancer Droplets 99th Percentile HTTP Response Time Metrics
      description: To retrieve Droplets 99th percentile HTTP response time in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_response_time_99p`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_queue_size:
    get:
      operationId: monitoring_get_lb_droplets_queue_size
      summary: Get Load Balancer Droplets Queue Size Metrics
      description: To retrieve Droplets queue size for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_queue_size`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_http_responses:
    get:
      operationId: monitoring_get_lb_droplets_http_responses
      summary: Get Load Balancer Droplets HTTP Rate Of Response Code Metrics
      description: To retrieve Droplets HTTP rate of response code for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_responses`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_connections:
    get:
      operationId: monitoring_get_lb_droplets_connections
      summary: Get Load Balancer Droplets Active Connections Metrics
      description: To retrieve Droplets active connections for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_connections`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_health_checks:
    get:
      operationId: monitoring_get_lb_droplets_health_checks
      summary: Get Load Balancer Droplets Health Check Status Metrics
      description: To retrieve Droplets health check status for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_health_checks`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/metrics/load_balancer/droplets_downtime:
    get:
      operationId: monitoring_get_lb_droplets_downtime
      summary: Get Load Balancer Droplets Downtime Status Metrics
      description: To retrieve Droplets downtime status for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_downtime`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/sinks/destinations:
    post:
      operationId: monitoring_create_destination
      summary: Create Logging Destination
      description: To create a new destination, send a POST request to `/v2/monitoring/sinks/destinations`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:create
    get:
      operationId: monitoring_list_destinations
      summary: List Logging Destinations
      description: To list all logging destinations, send a GET request to `/v2/monitoring/sinks/destinations`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/sinks/destinations/{destination_uuid}:
    get:
      operationId: monitoring_get_destination
      summary: Get Logging Destination
      description: To get the details of a destination, send a GET request to `/v2/monitoring/sinks/destinations/${destination_uuid}`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
    post:
      operationId: monitoring_update_destination
      summary: Update Logging Destination
      description: To update the details of a destination, send a PATCH request to `/v2/monitoring/sinks/destinations/${destination_uuid}`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:update
    delete:
      operationId: monitoring_delete_destination
      summary: Delete Logging Destination
      description: To delete a destination and all associated sinks, send a DELETE request to `/v2/monitoring/sinks/destinations/${destination_uuid}`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:delete
  /v2/monitoring/sinks:
    post:
      operationId: monitoring_create_sink
      summary: Create Sink
      description: 'To create a new sink, send a POST request to `/v2/monitoring/sinks`. Forwards logs from the

        resources identified in `resources` to the specified pre-existing destination.'
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:create
    get:
      operationId: monitoring_list_sinks
      summary: Lists all sinks
      description: To list all sinks, send a GET request to `/v2/monitoring/sinks`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
  /v2/monitoring/sinks/{sink_uuid}:
    get:
      operationId: monitoring_get_sink
      summary: Get Sink
      description: To get the details of a sink (resources and destination), send a GET request to `/v2/monitoring/sinks/${sink_uuid}`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:read
    delete:
      operationId: monitoring_delete_sink
      summary: Delete Sink
      description: To delete a sink, send a DELETE request to `/v2/monitoring/sinks/${sink_uuid}`.
      tags:
      - Monitoring
      security:
      - bearer_auth:
        - monitoring:delete
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: '## OAuth Authentication


        In order to interact with the DigitalOcean API, you or your application must

        authenticate.


        The DigitalOcean API handles this through OAuth, an open standard for

        authorization. OAuth allows you to delegate access to your account.

        Scopes can be used to grant full access, read-only access, or access to

        a specific set of endpoints.


        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)

        section of the DigitalOcean control panel for your account.


        An OAuth token functions as a complete authentication request. In effect, it

        acts as a substitute for a username and password pair.


        Because of this, it is absolutely **essential** that you keep your OAuth

        tokens secure. In fact, upon generation, the web interface will only display

        each token a single time in order to prevent the token from being compromised.


        DigitalOcean access tokens begin with an identifiable prefix in order to

        distinguish them from other similar tokens.


        - `dop_v1_` for personal access tokens generated in the control panel

        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)

        - `dor_v1_` for OAuth refresh tokens


        ### Scopes


        Scopes act like permissions assigned to an API token. These permissions

        determine what actions the token can perform. You can create API

        tokens that grant read-only access, full access, or limited access to

        specific endpoints by using custom scopes.


        Generally, scopes are designed to match HTTP verbs and common CRUD

        operations (Create, Read, Update, Delete).


        | HTTP Verb | CRUD Operation | Scope |

        |---|---|---|

        | GET | Read | `<resource>:read` |

        | POST | Create | `<resource>:create` |

        | PUT/PATCH | Update | `<resource>:update` |

        | DELETE | Delete | `<resource>:delete` |


        For example, creating a new Droplet by making a `POST` request to the

        `/v2/droplets` endpoint requires the `droplet:create` scope while

        listing Droplets by making a `GET` request to the `/v2/droplets`

        endpoint requires the `droplet:read` scope.


        Each endpoint below specifies which scope is required to access it when

        using custom scopes.


        ### How to Authenticate with OAuth


        In order to make an authenticated request, include a bearer-type

        `Authorization` header containing your OAuth token. All requests must be

        made over HTTPS.


        ### Authenticate with a Bearer Authorization Header


        ```

        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"

        ```

        '
